### ISSUE TITLE
Boyfriend's sprite freezes in its last animation when the camera pans to his opponent.

### ISSUE THREAD

**Issue by MagnaOpossum** [SystematicSkid/Funkin#1]
So instead of the boyfriend defaulting back to his normal head bob animation in-game, it will stay frozen on the last frame/animation he was in.

For example, let's say the bot last pressed the right key, the camera positions over to the dad. The boyfriend however is stuck in the animation or frame for when you pressed right. 

For another example, if he was in the head-bob animation before the camera pans over to the dad, he will be stuck in whatever frame his animation was in until it pans back to him.

**Comment by SystematicSkid** [comment]
Can confirm this happens.
This is due to the `holdTimer` field in the Character class.
Will need to figure out why it is not updating correctly.

**Comment by MagnaOpossum** [comment]
I'll do a bit of analyzing myself.

**Comment by SystematicSkid** [comment]
> I'll do a bit of analyzing myself.

The issue stems from [this function](https://github.com/ninjamuffin99/Funkin/blob/a8bea88494f628a12ccdeaf541de63cd67578610/source/Boyfriend.hx#L25) being spammed every tick, whereas it should only be called during and slightly after a key is pressed.

**Comment by MagnaOpossum** [comment]
Ah, I don't know how to actually code so I'm just reading what I understand.

**Comment by SystematicSkid** [comment]
I have gone ahead and pushed a fix.
https://github.com/SystematicSkid/Funkin/commit/fd93bbc6b14ee3c3573a8ce3e97e01a0441dd222
